// Bundle the macc-measure-authoring skill into a committed TS module so the hosted
// MCP can serve it (guide://measure). The skill is markdown on disk under
// `.claude/skills/macc-measure-authoring/`; stdio could read it at runtime, but the
// Deno Edge bundle and the Cloudflare Worker cannot — so we inline it at build time,
// exactly like the JSON authority data. esbuild (edge) and wrangler (worker) then
// inline `skill.generated.ts` with zero loader config.
//
//   npm run gen-skill           regenerate src/lib/measure/skill.generated.ts
//   npm run gen-skill -- --check verify it is in sync (CI / pre-deploy), no write
//
// Re-run after editing SKILL.md or any bundled reference, then `npm run build-edge`.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL_DIR = resolve(ROOT, '.claude/skills/macc-measure-authoring');
const OUT = resolve(ROOT, 'src/lib/measure/skill.generated.ts');

// References to bundle, in reading order. `_procedure-requirements.raw.md` is an orphan
// draft (stale terminology) and is intentionally excluded.
const REFERENCES = [
  'measure-types',
  'sectors',
  'conventions',
  'sourcing',
  'formula-ast',
  'abatement-modes',
  'potential',
  'checks',
];

/** Drop a leading YAML frontmatter block (`---` … `---`) — Claude Code harness metadata. */
function stripFrontmatter(md: string): string {
  if (!md.startsWith('---')) return md;
  const end = md.indexOf('\n---', 3);
  return end === -1 ? md : md.slice(md.indexOf('\n', end + 1) + 1).replace(/^\n+/, '');
}

function buildMarkdown(): string {
  const skill = stripFrontmatter(readFileSync(resolve(SKILL_DIR, 'SKILL.md'), 'utf8')).trimEnd();
  const refs = REFERENCES.map((name) => {
    const body = readFileSync(resolve(SKILL_DIR, 'references', `${name}.md`), 'utf8').trim();
    return `## reference: ${name}\n\n${body}`;
  });
  return [skill, '---', '# References', ...refs].join('\n\n') + '\n';
}

function render(markdown: string): string {
  const version = createHash('sha256').update(markdown).digest('hex').slice(0, 12);
  return `// GENERATED by scripts/gen-skill-bundle.ts — DO NOT EDIT.
// Source: .claude/skills/macc-measure-authoring/{SKILL.md,references/*.md}.
// Regenerate with \`npm run gen-skill\`, then \`npm run build-edge\`.
//
// The full measure-authoring guide (skill + references) served verbatim over MCP as
// the public \`guide://measure\` resource. Kept as one inlined module so every transport
// (stdio / Deno edge / Worker) ships the same text without runtime filesystem access.

export const SKILL_GUIDE = {
  version: ${JSON.stringify(version)},
  markdown: ${JSON.stringify(markdown)},
} as const;
`;
}

const markdown = buildMarkdown();
const next = render(markdown);
const check = process.argv.includes('--check');

if (check) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* missing → out of sync */ }
  if (current !== next) {
    console.error('skill bundle OUT OF SYNC — run `npm run gen-skill` and commit src/lib/measure/skill.generated.ts');
    process.exit(1);
  }
  console.log(`skill bundle in sync (${(markdown.length / 1024).toFixed(1)} kB, ${REFERENCES.length} references)`);
} else {
  writeFileSync(OUT, next);
  console.log(`wrote ${OUT} (${(markdown.length / 1024).toFixed(1)} kB, ${REFERENCES.length} references)`);
}
