// Precompile the measure JSON-schema validator to a STANDALONE module (no runtime codegen).
//
// ingest.ts gates every measure write with ajv. ajv's `.compile()` builds the validator via
// `new Function` — fine on Node/Deno, but Cloudflare Workers (the OAuth MCP transport the
// claude.ai connector uses) forbid code generation from strings, so a write through the Worker
// threw EvalError. ajv "standalone" emits the validator as plain JS at build time → zero runtime
// codegen, works on every transport. Re-run after editing data/measure.schema.json.
//
//   npm run gen-validator            regenerate src/lib/measure/measure-validator.generated.ts
//   npm run gen-validator -- --check verify it is in sync (CI / pre-deploy), no write
import Ajv2020 from 'ajv/dist/2020';
import standaloneCode from 'ajv/dist/standalone';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/lib/measure/measure-validator.generated.ts');
const schema = JSON.parse(readFileSync(resolve(ROOT, 'data/measure.schema.json'), 'utf8'));

// Same options ingest used at runtime, so validation behaviour is byte-identical to the audits.
const ajv = new Ajv2020({ code: { source: true, esm: true }, strict: false, allErrors: true });
const validate = ajv.compile(schema);
const code = standaloneCode(ajv, validate);
if (/new Function|eval\(/.test(code)) throw new Error('standalone output still contains runtime codegen — aborting');

const next = `// GENERATED by scripts/gen-measure-validator.ts — DO NOT EDIT.
// Standalone ajv validator for data/measure.schema.json (no runtime codegen — Worker-safe).
// Regenerate with \`npm run gen-validator\`.
// @ts-nocheck
/* eslint-disable */
${code}`;

const check = process.argv.includes('--check');
if (check) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* missing → out of sync */ }
  if (current !== next) {
    console.error('measure validator OUT OF SYNC — run `npm run gen-validator` and commit the generated file');
    process.exit(1);
  }
  console.log(`measure validator in sync (${(code.length / 1024).toFixed(1)} kB, no runtime codegen)`);
} else {
  writeFileSync(OUT, next);
  console.log(`wrote ${OUT} (${(code.length / 1024).toFixed(1)} kB standalone, no runtime codegen)`);
}
