#!/usr/bin/env python3
"""
Stage 3b: extract magic-number coefficients from Расчёты formulas onto the
`Допущения` sheet. Each occurrence becomes a new row; the literal in the
formula is replaced with a cell reference `'Допущения'!$F$N`.

The literal categorisation was reviewed with the project owner — three buckets:
  INLINE_ALLOW  — physical constants and algebraic glue, NOT extracted.
  IN_L          — clear engineering/economic assumptions (ПНР, ТОиР %, КИУМ,
                  CCS efficiency).
  IN_L_EXPERT   — unclear context, flagged review_status='expert' for the
                  expert pass.

Numerical equivalence is preserved bit-for-bit (the cached <v> on each formula
cell still matches because the replacement is value-identical), so etl.py
--check and the golden test stay green. Same XML-zip-surgery pattern as
Stages 1, 2 and 3a.
"""
from __future__ import annotations

import re
import shutil
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
XLSX = REPO / "MACC_KZ_29052026_rev.xlsx"
CALC_XML = "xl/worksheets/sheet3.xml"
DOP_XML = "xl/worksheets/sheet4.xml"
SHEET_NAME = "Допущения"

# Per the categorisation that was signed off:
INLINE_ALLOW = {"1", "2", "3", "6", "9", "10", "12", "16", "44", "100",
                "1000", "1000000", "1.163", "8760"}

# Map literal -> (auto-label-ru, expert?) for the clear bucket.
CLEAR_LABELS = {
    "0.3":   ("Доля ПНР", False),
    "0.005": ("ТОиР доля CAPEX (0.5%/год)", False),
    "0.015": ("ТОиР доля CAPEX (1.5%/год)", False),
    "0.02":  ("ТОиР доля CAPEX (2%/год)", False),
    "0.03":  ("ТОиР доля CAPEX (3%/год)", False),
    "0.04":  ("ТОиР доля CAPEX (4%/год)", False),
    "0.05":  ("ТОиР доля CAPEX (5%/год)", False),
    "0.8":   ("КИУМ ВИЭ", False),
    "0.95":  ("Эффективность CCS", False),
}
# Everything else extracted is EXPERT (label_ru autogenerated, source = formula).
EXPERT_LABEL_RU = "Коэффициент из формулы (требуется ревью)"


CELL_REF_RE = re.compile(r"\$?[A-Z]+\$?\d+(?::\$?[A-Z]+\$?\d+)?")
NUMERIC_RE = re.compile(r"(?<![A-Za-z\d\$\.])(\d+(?:\.\d+)?)(?![\dA-Za-z])")


def xml_escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ─────────────────────────────────────────────────────────────────────────────
# Magic literal extraction
# ─────────────────────────────────────────────────────────────────────────────

def find_magic_spans(formula: str) -> list[tuple[int, int, str]]:
    """Return [(start, end, literal)] for every magic-number operand in the
    formula. Cell refs are blanked out first so digits inside refs (C216) do
    not contribute, then NUMERIC_RE on the scrubbed-but-equal-length text
    yields stable positions.
    """
    scrubbed = CELL_REF_RE.sub(lambda m: "@" * len(m.group(0)), formula)
    spans = []
    for m in NUMERIC_RE.finditer(scrubbed):
        lit = m.group(1)
        if lit in INLINE_ALLOW:
            continue
        spans.append((m.start(), m.end(), lit))
    return spans


def replace_spans(formula: str, replacements: list[tuple[int, int, str]]) -> str:
    """Apply (start, end, new_text) edits to `formula` in reverse order so
    earlier spans don't shift."""
    out = formula
    for start, end, new in sorted(replacements, key=lambda x: -x[0]):
        out = out[:start] + new + out[end:]
    return out


# ─────────────────────────────────────────────────────────────────────────────
# Расчёты structural helpers (re-used from Stage 3a, lightweight inline copy)
# ─────────────────────────────────────────────────────────────────────────────

def parse_calc_rows(xml: str) -> dict[int, dict[str, tuple[str, str | None]]]:
    row_re = re.compile(r'<row r="(\d+)"[^>]*>(.*?)</row>', re.DOTALL)
    cell_re = re.compile(r'<c r="([A-Z]+)(\d+)"([^>]*)>(.*?)</c>', re.DOTALL)
    self_re = re.compile(r'<c r="([A-Z]+)(\d+)"([^>]*)/>')
    rows = {}
    for rm in row_re.finditer(xml):
        r = int(rm.group(1))
        cells = {}
        for cm in cell_re.finditer(rm.group(2)):
            cells[cm.group(1)] = (cm.group(3), cm.group(4))
        for cm in self_re.finditer(rm.group(2)):
            cells[cm.group(1)] = (cm.group(3), None)
        rows[r] = cells
    return rows


def read_shared_strings(zf: zipfile.ZipFile) -> list[str]:
    xml = zf.read("xl/sharedStrings.xml").decode("utf-8")
    si_re = re.compile(r"<si>(.*?)</si>", re.DOTALL)
    t_re = re.compile(r"<t[^>]*>([^<]*)</t>")
    out = []
    for m in si_re.finditer(xml):
        parts = [m2.group(1) for m2 in t_re.finditer(m.group(1))]
        out.append("".join(parts))
    return out


def get_cell_str_idx(cell):
    if cell is None:
        return None
    attrs, inner = cell
    if 't="s"' not in attrs or inner is None:
        return None
    m = re.search(r"<v>(\d+)</v>", inner)
    return int(m.group(1)) if m else None


def find_project_blocks(rows, shared):
    starts = []
    last_row = max(rows.keys())
    for r in sorted(rows.keys()):
        a = rows[r].get("A")
        if a is None:
            continue
        idx = get_cell_str_idx(a)
        if idx is None or idx >= len(shared):
            continue
        text = shared[idx].strip()
        m = re.match(r"^\[([^\]]+)\]", text)
        if m:
            starts.append((r, m.group(1)))
    out = []
    for i, (s, code) in enumerate(starts):
        e = starts[i + 1][0] if i + 1 < len(starts) else last_row + 1
        out.append((s, e, code))
    return out


def map_code_to_pid(rows, blocks):
    code_to_pid = {}
    for start, end, code in blocks:
        for r in range(start, end):
            d = rows.get(r, {}).get("D")
            if d is None:
                continue
            attrs, inner = d
            if not inner:
                continue
            m = re.search(r"<t>OUT_CAPEX_(\d+)</t>", inner)
            if m:
                code_to_pid[code] = int(m.group(1))
                break
    return code_to_pid


# ─────────────────────────────────────────────────────────────────────────────
# Допущения row emit
# ─────────────────────────────────────────────────────────────────────────────

def emit_dop_row_magic(
    n: int,
    pid: int,
    key: str,
    label_ru: str,
    value: str,
    review: str,
    source: str,
) -> str:
    """Inline-string version of Stage-3a's emit_dop_row, used for newly
    extracted magic coefficients. label_en/unit are left empty."""
    parts = [
        f'<c r="A{n}"><v>{pid}</v></c>',
        f'<c r="B{n}" t="inlineStr"><is><t>{"IN-L-EXPERT" if review else "IN-L"}</t></is></c>',
        f'<c r="C{n}" t="inlineStr"><is><t>{xml_escape(key)}</t></is></c>',
        f'<c r="D{n}" t="inlineStr"><is><t>{xml_escape(label_ru)}</t></is></c>',
        # E (label_en) empty
        f'<c r="F{n}"><v>{value}</v></c>',
        # G (unit) empty for magic
        f'<c r="H{n}" t="inlineStr"><is><t>{xml_escape(source)}</t></is></c>',
    ]
    if review:
        parts.append(f'<c r="I{n}" t="inlineStr"><is><t>{review}</t></is></c>')
    return f'<row r="{n}" spans="1:9">{"".join(parts)}</row>'


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> int:
    with zipfile.ZipFile(XLSX, "r") as zf:
        calc_xml = zf.read(CALC_XML).decode("utf-8")
        dop_xml = zf.read(DOP_XML).decode("utf-8")
        shared = read_shared_strings(zf)

    rows = parse_calc_rows(calc_xml)
    blocks = find_project_blocks(rows, shared)
    code_to_pid = map_code_to_pid(rows, blocks)

    def pid_for(r):
        for start, end, code in blocks:
            if start <= r < end:
                return code_to_pid.get(code)
        return None

    # Determine the next free Допущения row.
    last_dop_row = max(int(m.group(1))
                       for m in re.finditer(r'<row r="(\d+)"', dop_xml))
    next_row = last_dop_row + 1
    print(f"Допущения rows in use: {last_dop_row}. New rows start at {next_row}.")

    # Scan every formula cell in Расчёты!C, extract magic literals.
    extracted = 0
    new_dop_rows = []
    calc_cell_re = re.compile(
        r'(<c r="C(\d+)"([^>]*)>)<f>([^<]+)</f>(<v>[^<]*</v>)(</c>)',
    )
    new_calc_segments = []
    cursor = 0
    for m in calc_cell_re.finditer(calc_xml):
        new_calc_segments.append(calc_xml[cursor:m.start()])
        row_n = int(m.group(2))
        formula = m.group(4)
        spans = find_magic_spans(formula)
        if not spans:
            new_calc_segments.append(m.group(0))
            cursor = m.end()
            continue
        pid = pid_for(row_n)
        # Skip OUT formulas — they're INDEX/MATCH from Stage 2 and contain a
        # tag string ("OUT_CAPEX_1"); strings inside MATCH aren't numeric
        # operands so spans should be empty anyway. Defensive: bail if pid is
        # None.
        if pid is None:
            new_calc_segments.append(m.group(0))
            cursor = m.end()
            continue
        replacements = []
        for occ_i, (s, e, lit) in enumerate(spans, start=1):
            label_ru, _ = CLEAR_LABELS.get(lit, (EXPERT_LABEL_RU, True))
            is_expert = lit not in CLEAR_LABELS
            review = "expert" if is_expert else ""
            key = f"magic_{pid}_R{row_n}_{occ_i}"
            label_full = f"{label_ru} (проект {pid})" if not is_expert else label_ru
            new_dop_rows.append(emit_dop_row_magic(
                next_row, pid, key, label_full, lit, review, source=formula
            ))
            replacements.append((s, e, f"'{SHEET_NAME}'!$F${next_row}"))
            next_row += 1
            extracted += 1
        new_formula = replace_spans(formula, replacements)
        new_cell = (
            f'{m.group(1)}<f>{new_formula}</f>{m.group(5)}{m.group(6)}'
        )
        new_calc_segments.append(new_cell)
        cursor = m.end()
    new_calc_segments.append(calc_xml[cursor:])
    new_calc_xml = "".join(new_calc_segments)

    print(f"Magic literal occurrences extracted: {extracted}")
    if extracted == 0:
        print("ERROR: nothing extracted — check categorisation.", file=sys.stderr)
        return 1

    # Splice new rows into Допущения sheet (before </sheetData>).
    insertion = "".join(new_dop_rows)
    new_dop_xml = dop_xml.replace("</sheetData>", insertion + "</sheetData>", 1)
    # Update <dimension ref="A1:I{N}"/>
    new_dop_xml = re.sub(
        r'<dimension ref="A1:I\d+"/>',
        f'<dimension ref="A1:I{next_row - 1}"/>',
        new_dop_xml,
        count=1,
    )

    print(f"Patched Допущения XML: +{len(new_dop_rows)} rows -> "
          f"{len(new_dop_xml):,} bytes.")
    print(f"Patched Расчёты XML:   {len(new_calc_xml):,} bytes "
          f"(Δ={len(new_calc_xml)-len(calc_xml):+,}).")

    tmp = XLSX.with_suffix(".xlsx.tmp")
    with zipfile.ZipFile(XLSX, "r") as zin, zipfile.ZipFile(
        tmp, "w", zipfile.ZIP_DEFLATED
    ) as zout:
        replacements = {
            CALC_XML: new_calc_xml.encode("utf-8"),
            DOP_XML: new_dop_xml.encode("utf-8"),
        }
        for item in zin.infolist():
            payload = replacements.get(item.filename, zin.read(item.filename))
            zinfo = zipfile.ZipInfo(filename=item.filename, date_time=item.date_time)
            zinfo.compress_type = zipfile.ZIP_DEFLATED
            zinfo.external_attr = item.external_attr
            zout.writestr(zinfo, payload)

    shutil.move(tmp, XLSX)
    print(f"Saved {XLSX.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
